"""Tests for the -T ek fallback reader (EkPacket/EkReader/ek_argv).

The golden tests parse checked-in real tshark 4.6 output
(tests/data/ek_sample.ndjson, regenerated by tests/data/make_ek_sample.py)
without spawning tshark; the integration test spawns a real tshark against the
checked-in pcap and must agree with the golden parse.
"""

from __future__ import annotations

import shutil
from ipaddress import IPv4Address
from pathlib import Path

import pytest

from conftest import FakePacket
from remora.fields import Field, FieldRef, MultiField, Packet, RawPacket
from remora.reader.ek_reader import EkPacket, EkReader, ek_argv
from remora.reader.process import TsharkProcess

DATA_DIR = Path(__file__).resolve().parent / "data"
NDJSON_PATH = DATA_DIR / "ek_sample.ndjson"
PCAP_PATH = DATA_DIR / "ek_sample.pcap"

#: Fields probed when comparing a live tshark run against the golden parse.
#: Chosen to cover scalars, multi-occurrence arrays, booleans, and absence,
#: while staying stable across tshark versions.
PROBE_FIELDS = (
    "frame.number",
    "eth.src",
    "ip.src",
    "ip.dst",
    "ip.addr",
    "ip.ttl",
    "tcp.port",
    "tcp.srcport",
    "tcp.flags.syn",
    "tcp.flags.ack",
    "udp.port",
    "dns.qry.name",
    "dns.qry.type",
    "dns.count.queries",
    "dns.flags.response",
    "nosuch.field",
)


def _golden_lines() -> list[str]:
    return NDJSON_PATH.read_text().splitlines()


def _golden_packets() -> list[EkPacket]:
    return list(EkReader(_golden_lines()))


SRC_REF = FieldRef[IPv4Address]("ip.src", "FT_IPv4", False)
PORT_REF = FieldRef[int]("tcp.port", "FT_UINT16", True)
SYN_REF = FieldRef[bool]("tcp.flags.syn", "FT_BOOLEAN", False)


class FakeProto:
    """Stands in for a protocol class; #11's ProtocolBase builds these lazily."""

    _remora_packet: RawPacket

    src = Field(SRC_REF)
    port = MultiField(PORT_REF)
    syn = Field(SYN_REF)

    def __init__(self, packet: RawPacket) -> None:
        self._remora_packet = packet


class TestEkArgv:
    def test_value(self) -> None:
        assert ek_argv() == ["-T", "ek"]

    def test_returns_a_fresh_list(self) -> None:
        """Callers may extend the argv; mutations must not leak between calls."""
        argv = ek_argv()
        argv.append("-r")
        assert ek_argv() == ["-T", "ek"]


class TestGoldenSample:
    """Parse the checked-in real tshark 4.6 ek output (no subprocess)."""

    def test_packet_count_and_index_lines_skipped(self) -> None:
        lines = _golden_lines()
        index_lines = [line for line in lines if '"layers"' not in line]
        assert len(index_lines) == 3, "sample must interleave index metadata lines"
        assert all('"index"' in line for line in index_lines)
        assert len(list(EkReader(lines))) == 3

    def test_scalar_field_is_one_tuple(self) -> None:
        syn, syn_ack, dns = _golden_packets()
        assert syn.get_raw("ip.src") == ("10.0.0.1",)
        assert syn_ack.get_raw("ip.src") == ("10.0.0.2",)
        assert dns.get_raw("udp.dstport") == ("53",)

    def test_multi_value_field_is_a_tuple_in_wire_order(self) -> None:
        syn, _, dns = _golden_packets()
        assert syn.get_raw("tcp.port") == ("51234", "443")
        assert syn.get_raw("ip.addr") == ("10.0.0.1", "10.0.0.2")
        assert dns.get_raw("dns.qry.name") == ("example.com", "www.example.com")

    def test_absent_field_is_empty_tuple(self) -> None:
        syn, _, dns = _golden_packets()
        assert dns.get_raw("tcp.port") == ()  # UDP packet: no tcp layer
        assert syn.get_raw("dns.qry.name") == ()  # TCP packet: no dns layer

    def test_boolean_fields_normalize_to_1_and_0(self) -> None:
        syn, _, _ = _golden_packets()
        assert syn.get_raw("tcp.flags.syn") == ("1",)
        assert syn.get_raw("tcp.flags.ack") == ("0",)

    def test_deep_field_name_maps_through_key_mangling(self) -> None:
        """tcp.flags.syn lives at layers['tcp']['tcp_tcp_flags_syn']."""
        _, syn_ack, dns = _golden_packets()
        assert syn_ack.get_raw("tcp.flags.syn") == ("1",)
        assert dns.get_raw("dns.count.queries") == ("2",)

    def test_container_prefixed_field_is_found_across_layers(self) -> None:
        """_ws.expert.message has no "_ws" layer: its key is
        _ws_expert__ws_expert_message inside layers["tcp"]["_ws_expert"], so
        only the suffix-matching fallback across all layers can find it."""
        syn, syn_ack, _ = _golden_packets()
        assert syn.get_raw("_ws.expert.message") == (
            "Connection establish request (SYN): server port 443",
        )
        assert syn_ack.get_raw("_ws.expert.message") == (
            "Connection establish acknowledge (SYN+ACK): server port 443",
        )
        assert syn.get_raw("_ws.expert.severity") == ("2097152",)

    def test_unknown_field_on_real_packet_is_absent_not_an_error(self) -> None:
        """ek packets are complete: unknown fields are (), never FieldNotProjectedError."""
        syn, _, _ = _golden_packets()
        assert syn.get_raw("nosuch.field") == ()  # unknown layer
        assert syn.get_raw("ip.nosuch.subfield") == ()  # known layer, unknown key


class TestEkReaderLineHandling:
    def test_index_lines_and_blank_lines_are_skipped(self) -> None:
        lines = [
            '{"index":{"_index":"packets-2023-11-14"}}',
            '{"timestamp":"1","layers":{"ip":{"ip_ip_src":"10.0.0.1"}}}',
            "",
            '{"index":{"_index":"packets-2023-11-14"}}',
            '{"timestamp":"2","layers":{"ip":{"ip_ip_src":"10.0.0.2"}}}',
        ]
        packets = list(EkReader(lines))
        assert [p.get_raw("ip.src") for p in packets] == [("10.0.0.1",), ("10.0.0.2",)]

    def test_malformed_json_names_the_one_based_line_number(self) -> None:
        lines = [
            '{"index":{}}',
            '{"layers":{}}',
            '{"layers": <not json>}',
        ]
        with pytest.raises(ValueError, match="line 3"):
            list(EkReader(lines))

    def test_non_object_json_line_is_rejected_with_line_number(self) -> None:
        with pytest.raises(ValueError, match="line 1"):
            list(EkReader(["[1, 2, 3]"]))

    def test_iteration_is_lazy(self) -> None:
        """Packets before a malformed line are still yielded."""
        lines = ['{"layers":{"ip":{"ip_ip_ttl":"64"}}}', "garbage"]
        it = iter(EkReader(lines))
        assert next(it).get_raw("ip.ttl") == ("64",)
        with pytest.raises(ValueError, match="line 2"):
            next(it)


class TestEkPacketNormalization:
    def _packet(self, layers: dict[str, object]) -> EkPacket:
        return EkPacket(dict(layers))

    def test_booleans_become_1_and_0(self) -> None:
        pkt = self._packet({"tcp": {"tcp_tcp_flags_syn": True, "tcp_tcp_flags_ack": False}})
        assert pkt.get_raw("tcp.flags.syn") == ("1",)
        assert pkt.get_raw("tcp.flags.ack") == ("0",)

    def test_json_int_stringifies_without_trailing_point_zero(self) -> None:
        pkt = self._packet({"ip": {"ip_ip_ttl": 64}})
        assert pkt.get_raw("ip.ttl") == ("64",)

    def test_json_float_keeps_fractional_form(self) -> None:
        pkt = self._packet({"frame": {"frame_frame_time_delta": 1.5}})
        assert pkt.get_raw("frame.time_delta") == ("1.5",)

    def test_missing_layer_is_absent(self) -> None:
        assert self._packet({}).get_raw("ip.src") == ()

    def test_missing_key_in_present_layer_is_absent(self) -> None:
        assert self._packet({"ip": {}}).get_raw("ip.src") == ()

    def test_json_null_is_absent(self) -> None:
        pkt = self._packet({"tcp": {"tcp_tcp_connection_syn": None}})
        assert pkt.get_raw("tcp.connection.syn") == ()

    def test_array_of_nulls_contributes_nothing(self) -> None:
        pkt = self._packet({"ip": {"ip_ip_addr": [None, "10.0.0.1"]}})
        assert pkt.get_raw("ip.addr") == ("10.0.0.1",)

    def test_array_elements_normalize_like_scalars(self) -> None:
        pkt = self._packet({"dns": {"dns_dns_qry_type": [1, 28]}})
        assert pkt.get_raw("dns.qry.type") == ("1", "28")

    def test_unobserved_nested_array_flattens(self) -> None:
        """Never seen in tshark 4.6 output; flattened defensively, not an error."""
        pkt = self._packet({"ip": {"ip_ip_addr": [["10.0.0.1"], "10.0.0.2"]}})
        assert pkt.get_raw("ip.addr") == ("10.0.0.1", "10.0.0.2")

    def test_field_inside_nested_subtree_dict_is_found(self) -> None:
        """tshark nests expert-info fields in dicts like _ws_expert."""
        pkt = self._packet({"tcp": {"_ws_expert": {"tcp_tcp_analysis_retransmission": "1"}}})
        assert pkt.get_raw("tcp.analysis.retransmission") == ("1",)

    def test_direct_key_wins_over_nested_occurrence(self) -> None:
        pkt = self._packet({"ip": {"ip_ip_ttl": "64", "_sub": {"ip_ip_ttl": "1"}}})
        assert pkt.get_raw("ip.ttl") == ("64",)

    def test_subtree_dict_itself_is_not_a_field_value(self) -> None:
        pkt = self._packet({"tcp": {"tcp_tcp_flags": {"tcp_tcp_flags_syn": True}}})
        assert pkt.get_raw("tcp.flags") == ()

    def test_subtree_dict_does_not_shadow_nested_value_under_same_key(self) -> None:
        """A direct key hit whose value is a dict is a container, not a value:
        the search must continue and find the real (nested) occurrence."""
        pkt = self._packet(
            {"tcp": {"tcp_tcp_flags": {"tcp_tcp_flags_syn": True}, "_sub": {"tcp_tcp_flags": "2"}}}
        )
        assert pkt.get_raw("tcp.flags") == ("2",)

    def test_present_empty_string_is_distinct_from_absent(self) -> None:
        pkt = self._packet({"dns": {"dns_dns_qry_name": ""}})
        assert pkt.get_raw("dns.qry.name") == ("",)


class TestPacketContract:
    def test_satisfies_raw_packet_protocol(self) -> None:
        assert isinstance(EkPacket({}), RawPacket)
        # Packet is not runtime_checkable; conformance is verified statically
        # by mypy --strict, which CI runs over the test files too.
        _packet_view: Packet = EkPacket({})

    def test_getitem_builds_protocol_view(self) -> None:
        pkt = EkPacket(
            {
                "ip": {"ip_ip_src": "10.0.0.1"},
                "tcp": {"tcp_tcp_port": ["51234", "443"], "tcp_tcp_flags_syn": True},
            }
        )
        proto = pkt[FakeProto]
        assert isinstance(proto, FakeProto)
        assert proto._remora_packet is pkt
        assert proto.src == IPv4Address("10.0.0.1")
        assert proto.port == (51234, 443)
        assert proto.syn is True

    def test_descriptor_absent_semantics_through_getitem(self) -> None:
        proto = EkPacket({})[FakeProto]
        assert proto.src is None
        assert proto.port == ()

    def test_shared_semantics_with_dict_equivalent_fake_packet(self) -> None:
        """A FakePacket and an EkPacket built from the same logical data must
        give identical get_raw results — the shared RawPacket contract."""
        logical: dict[str, tuple[str, ...]] = {
            "ip.src": ("10.0.0.1",),
            "ip.addr": ("10.0.0.1", "10.0.0.2"),
            "tcp.port": ("51234", "443"),
            "tcp.flags.syn": ("1",),
            "tcp.flags.ack": ("0",),
            "dns.count.queries": ("2",),
        }
        fake = FakePacket(logical)
        ek = EkPacket(
            {
                "ip": {"ip_ip_src": "10.0.0.1", "ip_ip_addr": ["10.0.0.1", "10.0.0.2"]},
                "tcp": {
                    "tcp_tcp_port": ["51234", "443"],
                    "tcp_tcp_flags_syn": True,
                    "tcp_tcp_flags_ack": False,
                },
                "dns": {"dns_dns_count_queries": 2},
            }
        )
        for name in [*logical, "udp.port", "nosuch.field"]:
            assert ek.get_raw(name) == fake.get_raw(name), name


def _find_tshark() -> str | None:
    found = shutil.which("tshark")
    if found:
        return found
    fallback = "/opt/homebrew/bin/tshark"
    return fallback if Path(fallback).exists() else None


@pytest.mark.integration
def test_live_tshark_ek_matches_golden_parse() -> None:
    """Spawn real tshark via TsharkProcess + ek_argv; results must match the
    golden parse of the checked-in ndjson on every probe field."""
    tshark = _find_tshark()
    if tshark is None:
        pytest.skip("tshark binary not available")
    with TsharkProcess([tshark, "-r", str(PCAP_PATH), *ek_argv()]) as proc:
        live = list(EkReader(proc))
    golden = _golden_packets()
    assert len(live) == len(golden) == 3
    for i, (live_pkt, golden_pkt) in enumerate(zip(live, golden, strict=True)):
        for name in PROBE_FIELDS:
            assert live_pkt.get_raw(name) == golden_pkt.get_raw(name), f"packet {i}: {name}"
